"""
tools/report_tools.py
Member 4 — Report file writing tool.
"""
import logging
from pathlib import Path
from datetime import datetime
from langchain.tools import tool

logger = logging.getLogger(__name__)


@tool
def write_report_file(content: str, output_path: str) -> str:
    """
    Write a Markdown recruitment report to a local file.

    Creates all necessary parent directories automatically.
    Prepends a metadata header with timestamp and character count.
    Overwrites the file if it already exists.

    Args:
        content (str): Full Markdown content to write to the file.
        output_path (str): Relative or absolute path for the output
                           file (e.g. "outputs/report_2024.md").

    Returns:
        str: Absolute path of the written file.

    Raises:
        ValueError: If content is empty or contains only whitespace.
        OSError: If the file cannot be written due to permissions or disk errors.

    Example:
        >>> path = write_report_file("# Report\\n...", "outputs/report.md")
        >>> assert path.endswith(".md")
        >>> assert Path(path).exists()
    """
    if not content or not content.strip():
        raise ValueError("Report content is empty. Cannot write an empty report file.")

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().isoformat()
    header = (
        f"<!-- Generated by AI Recruitment MAS -->\n"
        f"<!-- Timestamp: {timestamp} -->\n"
        f"<!-- Characters: {len(content)} -->\n\n"
    )
    full_content = header + content

    path.write_text(full_content, encoding="utf-8")
    absolute = str(path.resolve())
    logger.info(f"[Tool:write_report_file] Saved {len(content)} chars to: {absolute}")
    return absolute
