"""
tools/report_tools.py
Member 4 — Report file writing tool.
"""
import logging
from pathlib import Path
from datetime import datetime
from langchain.tools import tool

logger = logging.getLogger(__name__)


@tool
def write_report_file(content: str, output_path: str) -> str:
    """
    Write a Markdown recruitment report to a local file.

    Creates all necessary parent directories automatically.
    Prepends a metadata comment header with the timestamp and character count.
    Overwrites the file if it already exists at the given path.

    Args:
        content (str): Full Markdown content to write to the file.
                       Must be non-empty and contain at least one non-whitespace
                       character.
        output_path (str): Relative or absolute path for the output file
                           (e.g. "outputs/report_20240101_120000.md").
                           Parent directories are created automatically.

    Returns:
        str: The absolute path of the written file as a string.

    Raises:
        ValueError: If content is empty or contains only whitespace.
        OSError: If the file cannot be written due to permission errors or
                 disk-full conditions.

    Example:
        >>> path = write_report_file("# Report\\nContent.", "outputs/report.md")
        >>> assert path.endswith(".md")
        >>> assert Path(path).exists()
        >>> assert Path(path).read_text().count("#") >= 1
    """
    if not content or not content.strip():
        raise ValueError(
            "Report content is empty. Cannot write an empty report file."
        )

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().isoformat()
    header = (
        f"<!-- Generated by AI Recruitment MAS -->\n"
        f"<!-- Timestamp : {timestamp} -->\n"
        f"<!-- Characters: {len(content)} -->\n\n"
    )
    full_content = header + content

    path.write_text(full_content, encoding="utf-8")
    absolute = str(path.resolve())
    logger.info(f"[Tool:write_report_file] Saved {len(content)} chars to: {absolute}")
    return absolute
