"""Tools for generating and writing screening reports."""

import logging
from datetime import datetime
import pathlib
from langchain.tools import tool

logger = logging.getLogger(__name__)

@tool
def write_report_file(content: str, output_path: str) -> str:
    """Write the final screening report to a file.

    Args:
        content: The full report content as a string.
        output_path: The file path where the report should be saved.

    Returns:
        str: The path to the written report file.
        
    Raises:
        ValueError: If content is empty or whitespace-only.
        
    Example:
        >>> path = write_report_file.invoke({"content": "# Report\\n...", "output_path": "outputs/report.md"})
    """
    if not content or not content.strip():
        raise ValueError("Report content is empty. Cannot write an empty report file.")
        
    path = pathlib.Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    
    header = (
        f"<!-- AUTO-GENERATED by AI Resume Screening MAS -->\n"
        f"<!-- Timestamp: {datetime.now().isoformat()} -->\n"
        f"<!-- Characters: {len(content)} -->\n\n"
    )
    full_content = header + content
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(full_content)
        
    logger.info(f"Report saved to {path.resolve()} with {len(content)} characters.")
    return str(path.resolve())
